version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 1080:1080
      - 1025:1025
    depends_on:
      - postgres
      - redis-queue
      - redis-cache

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=decide_development
      - ALLOW_HOSTS=/.*/
      - REDIS_URL=redis://redis-queue:6379
      - REDIS_CACHE_URL=redis://redis-cache:6380
      - DATABASE_HOST=postgres

  redis-queue:
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.0.12-alpine
    ports:
      - 6380:6380
    volumes:
      - redis-cache-data:/data

volumes:
  redis-queue-data:
  redis-cache-data:
  postgres-data: