name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Docker network
        run: docker network create mynetwork

      - name: Build containers
        run: docker-compose build

      - name: Run containers
        run: |
          docker-compose up -d
          docker network connect mynetwork gces-20231_redis-queue_1
          docker network connect mynetwork gces-20231_postgres_1

      - name: Wait for containers to start
        run: sleep 30

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose run app bash -c "bundle exec rails test"

  lint:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Rubocop
        run: docker-compose run app bash -c "bundle exec rubocop --fail-level warn"

      - name: Stop and remove containers
        run: docker-compose down

  deploy_simulation:
    runs-on: ubuntu-latest
    needs: [test, lint, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Simulate Deploy to GCP Cloud Run
        run: echo "Deployment to GCP Cloud Run simulated successfully!"     
 
