name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Docker network
        run: docker network create mynetwork

      - name: Build containers
        run: docker-compose build

      - name: Run containers
        run: |
          docker-compose up -d
          docker network connect mynetwork trabalho-individual-2023-1-victor-rayan_redis-queue_1
          docker network connect mynetwork trabalho-individual-2023-1-victor-rayan_postgres_1

      - name: Wait for containers
        run: sleep 30

      - name: Run Tests
        run: docker-compose run app bash -c "bundle exec rails test"

      - name: Run Lint
        run: |
          docker-compose run app bash -c "bundle exec rubocop --auto-correct"
          docker-compose run app bash -c "bundle exec rubocop --fail-level warn"
        continue-on-error: true

      - name: Stop and remove containers
        run: docker-compose down

  deploy_to_railway:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: 40628d33-ae12-4652-a048-a921aeb7756b
      RAILWAY_PROJECT_ID: fcde3a1a-a4d3-465a-8504-dbd049f2e58e
    steps:
      - name: Deploy to Railway
        run: |
          curl -X POST "https://api.railway.app/v1/projects/fcde3a1a-a4d3-465a-8504-dbd049f2e58e/deployments" -H "Authorization: Bearer 40628d33-ae12-4652-a048-a921aeb7756b"     
     
 
